"""Prove a committed release instead of trusting it.

``bpneat verify`` answers one question on the reader's own machine: does this
directory still say what it said when it was published? Four independent
checks, strongest first.

1. **Regeneration.** Every derived table is rebuilt from ``raw/runs/*.json`` in
   a temporary directory and byte-compared against the committed file. This is
   stronger than any checksum: a checksum proves a file has not changed, while
   regeneration proves the file is what the raw records actually imply.
2. **Checksums.** Every hash in ``sha256sums.txt`` is recomputed, and every file
   present is required to be accounted for.
3. **Manifest.** The suite is complete, the sealed test was evaluated, nothing
   failed.
4. **Fingerprint.** The seven science modules still hash to what the manifest
   recorded, so the code in this checkout is the code that produced the runs.

The release directory is opened read-only. Nothing here writes to it, and
nothing here reads a sealed test split.

**One known erratum, reported and not treated as corruption.**
``write_checksums`` runs inside ``final-test``, at which point the derived
tables on disk are whatever the last ``report`` left there. Both v2 tracks were
regenerated by ``report`` *after* the sealed test was evaluated, so their tables
gained test-derived columns that the checksum manifest never saw: track A lists
five derived files with four stale hashes, and track B omits the derived files
altogether. Check 1 verifies exactly those files by the stronger route, so a
stale or missing hash *on a file check 1 has already proven byte-exact* is
reported as an erratum rather than a failure. Every other mismatch — a raw
record, ``final-test.json``, ``manifest.json``, or any unaccounted file — is a
hard failure, and so is a stale hash on a derived file that check 1 could not
prove.
"""

from __future__ import annotations

import shutil
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from .record import code_fingerprint, sha256_file

# The files ``analysis.build`` derives from the raw records. These are the only
# files eligible for the checksum carve-out described in the module docstring,
# and only when check 1 has proven them byte-exact.
DERIVED_FILES = (
    "operation-usage.csv",
    "paired-effects.csv",
    "pareto-front.csv",
    "summary.csv",
    "summary.json",
)

CHECKSUM_FILE = "sha256sums.txt"


@dataclass
class Finding:
    """One observation. ``fatal`` decides the exit code; nothing else does."""

    check: str
    detail: str
    fatal: bool = True

    def __str__(self) -> str:
        return f"{'FAIL' if self.fatal else 'ERRATUM'}  {self.check}: {self.detail}"


@dataclass
class Report:
    track_dir: Path
    findings: list[Finding] = field(default_factory=list)
    lines: list[str] = field(default_factory=list)

    @property
    def failures(self) -> list[Finding]:
        return [f for f in self.findings if f.fatal]

    @property
    def errata(self) -> list[Finding]:
        return [f for f in self.findings if not f.fatal]

    @property
    def ok(self) -> bool:
        return not self.failures

    def fail(self, check: str, detail: str) -> None:
        self.findings.append(Finding(check, detail, fatal=True))

    def erratum(self, check: str, detail: str) -> None:
        self.findings.append(Finding(check, detail, fatal=False))

    def note(self, line: str) -> None:
        self.lines.append(line)


def _read_manifest(track_dir: Path) -> dict | None:
    import json

    path = track_dir / "manifest.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text())
    except ValueError:
        return None


def check_regeneration(track_dir: Path, report: Report) -> set[str]:
    """Rebuild every derived table from the raw records and byte-compare.

    Returns the set of derived filenames proven byte-exact. Runs entirely in a
    temporary directory: the release is never written to.
    """
    from .analysis import build

    runs_dir = track_dir / "raw" / "runs"
    if not runs_dir.is_dir():
        report.fail("regeneration", f"no raw records at {runs_dir}")
        return set()

    proven: set[str] = set()
    with tempfile.TemporaryDirectory(prefix="bpneat-verify-") as tmp:
        work = Path(tmp) / "release"
        (work / "raw").mkdir(parents=True)
        # Copy only the inputs a rebuild is allowed to see.
        shutil.copytree(runs_dir, work / "raw" / "runs")
        final = track_dir / "final-test.json"
        if final.exists():
            shutil.copy2(final, work / "final-test.json")

        try:
            build(work, progress=lambda *_: None)
        except SystemExit as exc:
            report.fail("regeneration", f"rebuild refused: {exc}")
            return set()
        except Exception as exc:
            # A malformed or foreign record must be reported, not raised: a
            # verifier that crashes tells the reader nothing about the release.
            report.fail(
                "regeneration",
                f"the raw records do not rebuild: {type(exc).__name__}: {exc}",
            )
            return set()

        for name in DERIVED_FILES:
            committed = track_dir / name
            rebuilt = work / name
            if not committed.exists():
                report.fail("regeneration", f"{name} is missing from the release")
                continue
            if not rebuilt.exists():
                report.fail("regeneration", f"{name} could not be rebuilt from raw records")
                continue
            if committed.read_bytes() != rebuilt.read_bytes():
                report.fail(
                    "regeneration",
                    f"{name} does not match what raw/runs/*.json implies",
                )
                continue
            proven.add(name)

    n_runs = len(list(runs_dir.glob("*.json")))
    report.note(
        f"  regeneration  {len(proven)}/{len(DERIVED_FILES)} derived files rebuilt "
        f"byte-identically from {n_runs} raw records"
    )
    return proven


def _parse_checksums(path: Path) -> list[tuple[str, str]]:
    entries = []
    for line in path.read_text().splitlines():
        if not line.strip():
            continue
        digest, _, name = line.partition("  ")
        if not name:
            continue
        entries.append((digest.strip(), name.strip()))
    return entries


def check_checksums(track_dir: Path, proven: set[str], report: Report) -> None:
    """Recompute every recorded hash, and account for every file present."""
    sums = track_dir / CHECKSUM_FILE
    if not sums.exists():
        report.fail("checksums", f"no {CHECKSUM_FILE} in the release")
        return

    entries = _parse_checksums(sums)
    if not entries:
        report.fail("checksums", f"{CHECKSUM_FILE} is empty or unparseable")
        return

    present = {
        str(p.relative_to(track_dir))
        for p in track_dir.rglob("*")
        if p.is_file() and p.name != CHECKSUM_FILE
    }

    matched = 0
    listed: set[str] = set()
    for digest, name in entries:
        listed.add(name)
        target = track_dir / name
        if not target.is_file():
            report.fail("checksums", f"{name} is listed but absent from the release")
            continue
        if sha256_file(target) == digest:
            matched += 1
            continue
        if name in DERIVED_FILES and name in proven:
            report.erratum(
                "checksums",
                f"{name} carries a stale hash — the manifest was written before "
                "the table was regenerated with the sealed-test columns; the "
                "committed bytes are proven correct by check 1",
            )
        else:
            report.fail("checksums", f"{name} does not match its recorded hash")

    for name in sorted(present - listed):
        if name in DERIVED_FILES and name in proven:
            report.erratum(
                "checksums",
                f"{name} is not listed in {CHECKSUM_FILE} — it did not exist yet "
                "when the manifest was written; the committed bytes are proven "
                "correct by check 1",
            )
        else:
            report.fail("checksums", f"{name} is present but not accounted for")

    report.note(
        f"  checksums     {matched}/{len(entries)} recorded hashes match, "
        f"{len(present)} files present"
    )


def check_manifest(track_dir: Path, report: Report) -> dict | None:
    manifest = _read_manifest(track_dir)
    if manifest is None:
        report.fail("manifest", "manifest.json is missing or unreadable")
        return None
    if not manifest.get("complete"):
        report.fail("manifest", "the suite is not marked complete")
    if not manifest.get("test_evaluated"):
        report.fail("manifest", "the sealed test was never evaluated for this release")
    failed = manifest.get("failed") or []
    if failed:
        report.fail("manifest", f"{len(failed)} runs are recorded as failed")
    missing = manifest.get("missing") or []
    if missing:
        report.fail("manifest", f"{len(missing)} planned runs are missing")
    report.note(
        f"  manifest      protocol {manifest.get('protocol_version')}, "
        f"track {manifest.get('track')}, complete={bool(manifest.get('complete'))}, "
        f"test_evaluated={bool(manifest.get('test_evaluated'))}, "
        f"failed={len(failed)}"
    )
    return manifest


def check_fingerprint(manifest: dict | None, report: Report) -> None:
    if manifest is None:
        return
    recorded = manifest.get("code_fingerprint")
    current = code_fingerprint()["combined"]
    if recorded is None:
        report.fail("fingerprint", "the manifest records no code fingerprint")
    elif recorded != current:
        report.fail(
            "fingerprint",
            f"the science modules in this checkout hash to {current[:16]}…, "
            f"but the suite ran under {recorded[:16]}…",
        )
    report.note(f"  fingerprint   {current}")


def verify(track_dir: Path) -> Report:
    """Run every check against one committed track directory. Read-only."""
    track_dir = Path(track_dir)
    report = Report(track_dir=track_dir)
    if not track_dir.is_dir():
        report.fail("release", f"{track_dir} is not a directory")
        return report

    proven = check_regeneration(track_dir, report)
    check_checksums(track_dir, proven, report)
    manifest = check_manifest(track_dir, report)
    check_fingerprint(manifest, report)
    return report


def render(report: Report, out=print) -> None:
    out(f"verifying {report.track_dir}")
    for line in report.lines:
        out(line)
    for finding in report.errata:
        out(f"  {finding}")
    for finding in report.failures:
        out(f"  {finding}")
    if report.ok:
        n = len(report.errata)
        tail = (
            f" ({n} known {'erratum' if n == 1 else 'errata'} in the checksum "
            "manifest, reported above)"
            if report.errata
            else ""
        )
        out(f"OK — the release regenerates from its own raw records{tail}")
    else:
        out(f"FAILED — {len(report.failures)} check(s) did not hold")
